on:
  push:
    tags:
      - '*.*.*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Set env
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up tmate
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - name: Update flake and meson version
      run: .github/workflows/nix-meson.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[gha] bump flake and meson version"